# Generated by Django 3.2.4 on 2021-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20210605_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='credit',
            new_name='acc_no_of_reciever',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='Acc_No',
            new_name='acc_no_of_sender',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='debit',
            new_name='amount_transferred',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='updated_balance',
            new_name='updated_balance_of_reciever',
        ),
        migrations.AddField(
            model_name='transfer',
            name='Date_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reciever_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='updated_balance_of_sender',
            field=models.IntegerField(default=0),
        ),
    ]
